name: the_first_one
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttertoast: ^2.0.6
  dio: ^1.0.0 #latest version
  transparent_image: 0.1.0
  flutter_swiper : ^1.0.4
  flutter_webview_plugin: ^0.1.4
  json_annotation: ^1.0.0
#  json_annotation: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.10.0
  json_serializable: ^1.0.0
#  build_runner: ^0.9.0
#  json_serializable: ^0.5.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/images/ic_no_avatar.png
      - assets/images/illustration_1.jpg
      - assets/images/illustration_2.jpg
      - assets/images/illustration_3.jpg
      - assets/images/illustration_4.jpg
      - assets/images/illustration_5.jpg
      - assets/images/illustration_6.jpg
      - assets/images/illustration_7.jpg
      - assets/images/illustration_8.jpg
      - assets/images/illustration_9.jpg
      - assets/images/illustration_10.jpg
      - assets/images/illustration_11.jpg
      - assets/images/illustration_12.jpg
      - assets/images/illustration_13.jpg
      - assets/images/illustration_14.jpg
      - assets/images/illustration_15.jpg
      - assets/images/illustration_16.jpg
      - assets/images/illustration_17.jpg
      - assets/images/illustration_18.jpg
      - assets/images/illustration_19.jpg
      - assets/images/illustration_20.jpg
      - assets/images/illustration_21.jpg
      - assets/images/illustration_22.jpg
      - assets/images/illustration_23.jpg
      - assets/images/illustration_24.jpg
      - assets/images/illustration_25.jpg
      - assets/images/illustration_26.jpg
      - assets/images/illustration_27.jpg
      - assets/images/illustration_28.jpg
      - assets/images/illustration_29.jpg
      - assets/images/illustration_30.jpg
      - assets/images/illustration_31.jpg
      - assets/images/illustration_32.jpg
      - assets/images/illustration_33.jpg
      - assets/images/illustration_34.jpg
      - assets/images/illustration_35.jpg

      - assets/images/ic_wechat.png
      - assets/images/ic_circle.png
      - assets/images/ic_dot3.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
